# Generated by Django 5.2.17 on 2026-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can view the accounts of the Corporation of their own main'), ('view_all', 'Can view all accounts and Corporations of the Alliance'), ('manage_settings', 'Can change the Alliance and the checks')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
