# Generated by Django 5.2.17 on 2026-09-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0001_initial'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stale_after_days', models.PositiveSmallIntegerField(blank=True, help_text='Days after which a section of the corptools Corporation audit counts as stale. Empty: the same limit corptools uses for characters.', null=True, verbose_name='Stale after (days)')),
                ('disabled_checks', models.JSONField(blank=True, default=list)),
                ('disabled_services', models.JSONField(blank=True, default=list)),
                ('alliance', models.ForeignKey(blank=True, help_text='The Alliance whose accounts and Corporations are monitored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eveonline.eveallianceinfo', verbose_name='Alliance')),
            ],
            options={
                'verbose_name': 'Configuration',
                'default_permissions': (),
            },
        ),
    ]
