# Generated by Django 5.2.17 on 2026-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0002_snapshot_monitorconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProblemsFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('reversed_logic', models.BooleanField(default=False, help_text='Pass accounts that HAVE problems instead of those without.')),
                ('include_corporation', models.BooleanField(default=False, help_text='Also count the problems of the Corporation of the main.')),
            ],
            options={
                'verbose_name': 'Smart Filter: Auth Monitor problems',
                'verbose_name_plural': 'Smart Filter: Auth Monitor problems',
            },
        ),
        migrations.AddField(
            model_name='monitorconfiguration',
            name='excluded_character_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfiguration',
            name='excluded_character_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfiguration',
            name='excluded_corporation_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfiguration',
            name='excluded_corporation_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfiguration',
            name='fetch_members',
            field=models.BooleanField(default=True, help_text="Reads each Corporation's member list with a token corptools already has, to show members that are not registered in Auth.", verbose_name='Fetch member lists from ESI'),
        ),
    ]
