# Generated by Django 5.2.17 on 2026-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0003_accountproblemsfilter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorconfiguration',
            name='fetch_members',
            field=models.BooleanField(default=True, help_text="Reads each Corporation's member list and Director roles with tokens corptools already has, to show members that are not registered in Auth and Directors without a token.", verbose_name='Fetch data from ESI'),
        ),
    ]
