# Generated by Django 5.2.17 on 2026-09-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0004_fetch_members_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountProblemsFilter',
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view the accounts of the Corporation of their own main'), ('view_all', 'Can view all accounts and Corporations of the Alliance'), ('manage_settings', 'Can change the Alliance and the checks'), ('view_own', 'Can view their own account'))},
        ),
    ]
