# Generated by Django 5.2.17 on 2026-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0005_own_account_without_smart_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfiguration',
            name='alliance_characters_only',
            field=models.BooleanField(default=False, help_text='Checks, shows and counts only the characters of an account that are in the Alliance; alts elsewhere are left out.', verbose_name='Only characters in the Alliance'),
        ),
    ]
