# Generated by Django 5.2.17 on 2026-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0006_alliance_characters_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProblemsFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('reversed_logic', models.BooleanField(default=False, help_text='Pass accounts whose characters HAVE problems instead of those without.')),
            ],
            options={
                'verbose_name': 'Smart Filter: Auth Monitor character problems',
                'verbose_name_plural': 'Smart Filter: Auth Monitor character problems',
            },
        ),
    ]
