# Generated by Django 5.2.17 on 2026-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_auth_monitor', '0007_character_problems_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfiguration',
            name='member_notice',
            field=models.TextField(blank=True, help_text='Shown as an info box on My account and My Corporation. Leave it empty to show none.', verbose_name='Notice to members'),
        ),
    ]
